version: '3.7'
services:
  task-management-postgres:
    image: postgres:14
    container_name: "${APP_NAME}_POSTGRES"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - task-management-service
  
  task-management-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: "${APP_NAME}_APP"
    image: app-task-management
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      DB_HOST: task-management-postgres
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - task-management-postgres
    networks:
      - task-management-service
networks:
  task-management-service:
volumes:
  pg_data: