version: '3'
services:
  task-management-postgres:
    image: postgres:14
    container_name: '${APP_NAME}_POSTGRES'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - task-management-network

  task-management-adminer:
    image: adminer
    container_name: '${APP_NAME}_ADMINER'
    ports:
      - '3001:8080'
    networks:
      - task-management-network

  task-management-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: '${APP_NAME}_APP'
    image: app-task-management-dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      DB_HOST: task-management-postgres
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - task-management-postgres
    networks:
      - task-management-network

networks:
  task-management-network:

volumes:
  pg_data:
